LIPAMPIRI/LIPAMPIRI/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),  
    path('', include('journal.urls')),
    path('logbook', include('drivers_logbook.urls')),
    path('api/', include('journal.urls')),
    
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

LIPAMPIRI/accounts/urls.py
from django.urls import path
from .views import CustomRegisterView, CustomLoginView, CustomLogoutView, ProfileView, ProfileEditView, SettingsView, SettingsEditView, DeleteProfileView,DeleteSettingsView, MembershipView, MembershipEditView, DeleteMembershipView, AccountView, SearchView

app_name = 'accounts'

urlpatterns = [
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', CustomLogoutView.as_view(), name='logout'),
    path('search/', SearchView, name='search_view'),
    
    path('account/', AccountView, name='account'),
    
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile/edit/<int:pk>/', ProfileEditView.as_view(), name='profile_edit'),
    path('delete-profile/', DeleteProfileView.as_view(), name='delete_profile'),


    path('settings/', SettingsView.as_view(), name='settings'),
    path('settings/edit/<int:pk>/', SettingsEditView.as_view(), name='settings_edit'),
    path('delete-settings/', DeleteSettingsView.as_view(), name='delete_profile'),


    path('membership/', MembershipView.as_view(), name='membership'),
    path('membership/edit/<int:pk>/', MembershipEditView.as_view(), name='membership_edit'),
    path('membership/delete/', DeleteMembershipView.as_view(), name='delete_membership'),
]

LIPAMPIRI/journal/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import EntryViewSet

router = DefaultRouter()
router.register(r'entries', EntryViewSet)

app_name = 'journal'
urlpatterns = [
    path('', include(router.urls)),
]

LIPAMPIRI/templates/snippets/footer.html
<footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-muted">© 2022 khotsoT, Inc</span>
    </div>

    <ul class="nav col-md-4 justify-content-end list-unstyled d-flex">
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#twitter"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"></use></svg></a></li>
      <li class="ms-3"><a class="text-muted" href="#"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"></use></svg></a></li>
    </ul>
</footer>

LIPAMPIRI/templates/snippets/nav.html
{% load static %}
<header class="p-3 mb-3 border-bottom bg-dark text-white">
  <div class="container">
    <div
      class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start"
    >
      <a
        href="/"
        class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none"
      >
        Project
      </a>

      <ul
        class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0"
      >
        <li>
          <a
            href="{% url 'journal:entry-list' %}"
            class="nav-link px-2 link-secondary text-light"
            >Overview</a
          >
        </li>

        <!-- <li><a href="#" class="nav-link px-2 link-secondary text-light">Other Link</a></li> -->
      </ul>

      <form
        class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3"
        role="search"
        action="{% url 'accounts:search_view' %}"
        method="get"
      >
        <input
          type="search"
          class="form-control"
          placeholder="Search..."
          aria-label="Search"
          name="q"
        />
      </form>

      {% if user.is_authenticated %}
      <div class="dropdown text-end">
        <a
          href="#"
          class="d-block"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
          {% if user.profile_image %}
          <img
            src="{{ user.profile_image.url }}"
            width="32"
            height="32"
            class="rounded-circle"
          />
          {% else %}
          <img
            src="{% static 'images/profile/default_profile.png' %}"
            width="32"
            height="32"
            class="rounded-circle"
          />
          {% endif %}
        </a>
        <ul class="dropdown-menu text-small bg-dark">
          <li>
            <a
              class="dropdown-item text-light"
              href="{% url 'accounts:account' %}"
              >{{ user.username }}</a
            >
          </li>
          <li><hr class="dropdown-divider" /></li>
          <li>
            <a
              class="dropdown-item text-light"
              href="{% url 'accounts:settings' %}"
              >Settings</a
            >
          </li>
          <li>
            <a
              class="dropdown-item text-light"
              href="{% url 'accounts:profile' %}"
              >Profile</a
            >
          </li>
          <li><hr class="dropdown-divider" /></li>
          <li>
            <a
              class="dropdown-item text-light"
              href="{% url 'accounts:logout' %}"
              >Sign out</a
            >
          </li>
        </ul>
      </div>
      {% else %}
      <!-- <div class="dropdown text-end">
              <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                  <li><a href="{% url 'accounts:register' %}" class="nav-link px-2 link-light">Register</a></li>
                  <li><a href="{% url 'accounts:login' %}" class="nav-link px-2 link-light">Login</a></li>
              </ul>
          </div> -->
      {% endif %}
    </div>
  </div>
</header>

{% block style %}
<style>
  /* Custom hover styles for links */
  .link-light:focus,
  .link-light:hover {
    color: #565e64 !important;
    background-color: none !important;
  }

  .dropdown-item:focus,
  .dropdown-item:hover {
    color: #565e64 !important;
    background-color: transparent !important;
  }
</style>
{% endblock %}

LIPAMPIRI/templates/snippets/sidenav.html
<div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 280px;">
    <a href="/" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi pe-none me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
      <span class="fs-4">Sidebar</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
      <li class="nav-item">
        <a href="#" class="nav-link active" aria-current="page">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#home"></use></svg>
          Home
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#speedometer2"></use></svg>
          Dashboard
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#table"></use></svg>
          Orders
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#grid"></use></svg>
          Products
        </a>
      </li>
      <li>
        <a href="#" class="nav-link link-dark">
          <svg class="bi pe-none me-2" width="16" height="16"><use xlink:href="#people-circle"></use></svg>
          Customers
        </a>
      </li>
    </ul>
    <hr>
    <div class="dropdown">
      <a href="#" class="d-flex align-items-center link-dark text-decoration-none dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
        <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
        <strong>mdo</strong>
      </a>
      <ul class="dropdown-menu text-small shadow">
        <li><a class="dropdown-item" href="#">New project...</a></li>
        <li><a class="dropdown-item" href="#">Settings</a></li>
        <li><a class="dropdown-item" href="#">Profile</a></li>
        <li><hr class="dropdown-divider"></li>
        <li><a class="dropdown-item" href="#">Sign out</a></li>
      </ul>
    </div>
</div>